######################## default configuration ####################
baseURL = "https://unplastify-youth.netlify.app"
canonifyURLs = "true"
title = "安普拉絲特φ青少年去塑聯盟"
theme = "andromeda-light"
# post pagination
pagination.pagerSize = "6"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "G-7F5KEHWZNM" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
# disqusShortname = "" # get your shortname form here : https://disqus.com

############################# Modules ##############################
[module]
[module.hugoVersion]
extended = true
min = "0.83.1"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON","WebAppManifest"]


[imaging]
quality = 90

[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

[markup]
[markup.goldmark.renderer]
unsafe= true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
