# main menu
[[main]]
name = "首頁"
url = ""
weight = 1

[[main]]
name = "關於我們"
url = "about/"
weight = 2


  #[[main]]
  #parent = "行動與教育"
  #name = "去塑行動"
  #url = "/categories/去塑行動"
  #weight = 1

  #[[main]]
  #parent = "行動與教育"
  #name = "環境教育"
  #url = "/categories/環境教育"
  #weight = 7

[[main]]
weight = 6
name = "去塑行動"
url = "/categories/去塑行動"

[[main]]
weight = 6
name = "環境教育"
url = "/categories/環境教育"

[[main]]
weight = 6
name = "知識分享"
url = "/categories/知識分享"
  
[[main]]
name = "聯絡我們"
url = "contact/"
weight = 7


# footer menu
[[footer]]
name = "關於我們"
url = "about/"
weight = 1

[[footer]]
name = "去塑行動"
url = "/categories/去塑行動/"
weight = 2

[[footer]]
name = "環境教育"
url = "/categories/環境教育/"
weight = 3

[[footer]]
name = "知識分享"
url = "/categories/知識分享/"
weight = 4